### ISSUE TITLE
Design a better login UI for the extension

### ISSUE THREAD

**Issue by xlogix** [fnplus/footsteps-extension#21]
Add Google, Email & Github Sign-in

**Comment by Samarjiit** [comment]
hi @xlogix assign me this issue

**Comment by xlogix** [comment]
Assigned!

**Comment by saloniankita** [comment]
Can I work on this issue @xlogix ?

**Comment by xlogix** [comment]
Assigned!

**Comment by silenteyesoncode** [comment]
can I work On this issue?

**Comment by saloniankita** [comment]
@silenteyesoncode I'm working on it

**Comment by saloniankita** [comment]
@xlogix Where can I find the API key, authDomain and other information. I filled the form for access to firebase project but got no response.

**Comment by xlogix** [comment]
The info is the same as the footsteps-app repo. Check out its readme. And, I'll also add you to the Firebase project.

**Comment by kavyashree1903** [comment]
Can I work on this @xlogix

**Comment by xlogix** [comment]
Sure!

**Comment by kavyashree1903** [comment]
![Screenshot from 2020-12-17 19-06-00](https://user-images.githubusercontent.com/65967490/102494657-00a73a00-409b-11eb-9a48-b7aefe658a1a.png)
I am getting this error on setting up the repo @xlogix

**Comment by xlogix** [comment]
Is it the vulnerabilities message? Can you tell me what exact error you're facing?

**Comment by kavyashree1903** [comment]
> footsteps-extension@1.0.0 build /home/kavya/footsteps-extension
> node ./scripts/build.js

/home/kavya/footsteps-extension/scripts/build.js:10
const directoriesToCopy = ["src/auth", "src/popup/"", "public"];
                                                   ^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! footsteps-extension@1.0.0 build: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the footsteps-extension@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kavya/.npm/_logs/2020-12-18T20_12_58_006Z-debug.log

@xlogix

**Comment by xlogix** [comment]
It should work now! Please pull and do npm install again!

**Comment by kavyashree1903** [comment]
sure!
