### ISSUE TITLE
npm run build fails.

### ISSUE THREAD

**Issue by salhasalman** [fnplus/footsteps-extension#46]
C:\Users\User\footsteps-extension\footsteps-extension>npm run build

> footsteps-extension@1.0.0 build C:\Users\User\footsteps-extension\footsteps-extension
> node ./scripts/build.js

C:\Users\User\footsteps-extension\footsteps-extension\scripts\build.js:10
const directoriesToCopy = ["src/auth", "src/popup/"", "public"];
                                                   ^^^^

SyntaxError: Unexpected string
[90m    at wrapSafe (internal/modules/cjs/loader.js:1054:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1102:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! footsteps-extension@1.0.0 build: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the footsteps-extension@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-06-14T04_39_48_951Z-debug.log

**Comment by X3NOSIZ** [comment]
Follow these steps, it might fix your problem.

• Start from scratch.
• Check if node.js root file-path is added to the System/env-path.
• npm fix (not recommended)
• Reinstall node.js to the latest
• cd into the project file, then follow regular installation process.

What I personally think is that, this problem arose because of missing paths. If possible have a log check of the debug.log file inside npm-cache_logs.

**Comment by xlogix** [comment]
Let me take a look.
